//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdfforge.PDFCreator.Core.Controller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Testpage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Testpage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pdfforge.PDFCreator.Core.Controller.Testpage", typeof(Testpage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!PS-Adobe-1.0
        ///%%Creator: PDFCreator
        ///%%For: PDFCreator
        ///%%Title: Testpage - PDFCreator
        ///%%Pages: 1
        ///%%PageOrder: Ascend
        ///%%DocumentMedia: A4 595 842 0 () ()
        ///%%Orientation: Portrait
        ///%%BoundingBox: 0 0 595 842
        ///%%DocumentFonts: Arial, Helvetica, Helvetica-Bold, Times-Roman
        ///%%EndComments
        ///
        ////Reencsmalldict 12 dict def
        ////ReEncodeSmall
        ///{ Reencsmalldict begin
        ///    /NewCodesAndNames exch def
        ///    /NewFontName exch def
        ///    /BaseFontName exch def
        ///    /BaseFontDict
        ///    BaseFontName findfont def
        ///    /NewFont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestPage {
            get {
                return ResourceManager.GetString("TestPage", resourceCulture);
            }
        }
    }
}
