//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pdfforge.PDFCreator.Core.Controller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Testpage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Testpage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pdfforge.PDFCreator.Core.Controller.Testpage", typeof(Testpage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!PS-Adobe-3.0
        ///%%Creator: cairo 1.15.6 (http://cairographics.org)
        ///%%CreationDate: Fri Sep 01 14:17:36 2017
        ///%%Pages: 1
        ///%%DocumentData: Clean7Bit
        ///%%LanguageLevel: 3
        ///%%DocumentMedia: A4 595 842 0 () ()
        ///%%BoundingBox: 0 0 596 842
        ///%%EndComments
        ///%%BeginProlog
        ////languagelevel where
        ///{ pop languagelevel } { 1 } ifelse
        ///3 lt { /Helvetica findfont 12 scalefont setfont 50 500 moveto
        ///  (This print job requires a PostScript Language Level 3 printer.) show
        ///  showpage quit } if
        ////q { gsave } bind def
        ////Q { grestore } bind def
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestPage {
            get {
                return ResourceManager.GetString("TestPage", resourceCulture);
            }
        }
    }
}
