//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFCreator.TestUtilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFCreator.TestUtilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Attachment3PagesPDF {
            get {
                object obj = ResourceManager.GetObject("Attachment3PagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Background3PagesPDF {
            get {
                object obj = ResourceManager.GetObject("Background3PagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CertificationFile_ExpiredP12 {
            get {
                object obj = ResourceManager.GetObject("CertificationFile_ExpiredP12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CertificationFileP12 {
            get {
                object obj = ResourceManager.GetObject("CertificationFileP12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Cover2PagesPDF {
            get {
                object obj = ResourceManager.GetObject("Cover2PagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Cover2PagesSixEmptyPagesAttachment3PagesPDF {
            get {
                object obj = ResourceManager.GetObject("Cover2PagesSixEmptyPagesAttachment3PagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Cover2PagesSixEmptyPagesPDF {
            get {
                object obj = ResourceManager.GetObject("Cover2PagesSixEmptyPagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElevenTextPagesPS {
            get {
                object obj = ResourceManager.GetObject("ElevenTextPagesPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EmptyPagePS {
            get {
                object obj = ResourceManager.GetObject("EmptyPagePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FourRotatingPDFCreatorTestpagesPDF {
            get {
                object obj = ResourceManager.GetObject("FourRotatingPDFCreatorTestpagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LandscapePagePS {
            get {
                object obj = ResourceManager.GetObject("LandscapePagePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PageRotation0PDF {
            get {
                object obj = ResourceManager.GetObject("PageRotation0PDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PageRotation180PDF {
            get {
                object obj = ResourceManager.GetObject("PageRotation180PDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PageRotation270PDF {
            get {
                object obj = ResourceManager.GetObject("PageRotation270PDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PageRotation90PDF {
            get {
                object obj = ResourceManager.GetObject("PageRotation90PDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PDFCreatorTestpageJPG {
            get {
                object obj = ResourceManager.GetObject("PDFCreatorTestpageJPG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PDFCreatorTestpage_GS9_19_PDF {
            get {
                object obj = ResourceManager.GetObject("PDFCreatorTestpage_GS9_19_PDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PDFCreatorTestpage_GS9_19_PDF_A_1b {
            get {
                object obj = ResourceManager.GetObject("PDFCreatorTestpage_GS9_19_PDF_A_1b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PDFCreatorTestpage_GS9_19_PDF_A_2b {
            get {
                object obj = ResourceManager.GetObject("PDFCreatorTestpage_GS9_19_PDF_A_2b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PDFCreatorTestpage_GS9_19_PDF_X {
            get {
                object obj = ResourceManager.GetObject("PDFCreatorTestpage_GS9_19_PDF_X", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PDFCreatorTestpagePNG {
            get {
                object obj = ResourceManager.GetObject("PDFCreatorTestpagePNG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PDFCreatorTestpagePS {
            get {
                object obj = ResourceManager.GetObject("PDFCreatorTestpagePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PDFCreatorTestpageTIF {
            get {
                object obj = ResourceManager.GetObject("PDFCreatorTestpageTIF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                            PDF                                                         PDFCreator
        ///                                                                                       Opensource
        ///                                        Now
        ///                                   PDFCreator 3.0.0.0
        ///                                   Date:                                                                 25/04/2017 13:27:30
        ///                                   Authors:                                              [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PDFCreatorTestpageTXT {
            get {
                return ResourceManager.GetString("PDFCreatorTestpageTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PortraitLandscapeLandscapeLandscapePortraitPDF {
            get {
                object obj = ResourceManager.GetObject("PortraitLandscapeLandscapeLandscapePortraitPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PortraitPagePS {
            get {
                object obj = ResourceManager.GetObject("PortraitPagePS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rem Script copies multiple files into the directory given as first parameter 
        ///if %1 == &quot;&quot; goto end
        ///if %2 == &quot;&quot; goto end 
        ///set targetDir=%1
        ///md %targetDir%
        ///:copy
        ///if %2 == &quot;&quot; goto end
        ///copy %2 %targetDir%
        ///shift
        ///goto copy
        ///:end.
        /// </summary>
        public static string ScriptCopyFilesToDirectoryCMD {
            get {
                return ResourceManager.GetString("ScriptCopyFilesToDirectoryCMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SixEmptyPagesAttachment3PagesPDF {
            get {
                object obj = ResourceManager.GetObject("SixEmptyPagesAttachment3PagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SixEmptyPagesPDF {
            get {
                object obj = ResourceManager.GetObject("SixEmptyPagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ThreePDFCreatorTestpagesPDF {
            get {
                object obj = ResourceManager.GetObject("ThreePDFCreatorTestpagesPDF", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
