//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace pdfforge.PDFCreator.Core {
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class CoreResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("pdfforge.PDFCreator.Core.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] eciRGB_v2 {
            get {
                object obj = ResourceManager.GetObject("eciRGB_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ISOcoated_v2_300_eci {
            get {
                object obj = ResourceManager.GetObject("ISOcoated_v2_300_eci", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ISOcoated_v2_grey1c_bas {
            get {
                object obj = ResourceManager.GetObject("ISOcoated_v2_grey1c_bas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die %!
        ///% This is a sample prefix file for creating a PDF/A document.
        ///% Feel free to modify entries marked with &quot;Customize&quot;.
        ///
        ///% This assumes an ICC profile to reside in the file (ISO Coated sb.icc),
        ///% unless the user modifies the corresponding line below.
        ///
        ///% Define entries in the document Info dictionary :
        ///
        ////ICCProfile [ICC_PROFILE]
        ///def
        ///
        ///[ /Title (Title)                  % Customize.
        ///  /DOCINFO pdfmark
        ///
        ///% Define an ICC profile :
        ///
        ///[/_objdef {icc_PDFA} /type /stream /OBJ pdfmark
        ///[{icc_PDFA} &lt;&lt;/N systemdict /Proces [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PdfaDefinition {
            get {
                return ResourceManager.GetString("PdfaDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap pdfforge_logo {
            get {
                object obj = ResourceManager.GetObject("pdfforge_logo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die %!
        ///% This is a sample prefix file for creating a PDF/X-3 document.
        ///% Feel free to modify entries marked with &quot;Customize&quot;.
        ///
        ///% This assumes an ICC profile to reside in the file (ISO Coated sb.icc),
        ///% unless the user modifies the corresponding line below.
        ///
        ///systemdict /ProcessColorModel known {
        ///  systemdict /ProcessColorModel get dup /DeviceGray ne exch /DeviceCMYK ne and
        ///} {
        ///  true
        ///} ifelse
        ///{ (ERROR: ProcessColorModel must be /DeviceGray or DeviceCMYK.)=
        ///  /ProcessColorModel cvx /rangecheck signalerror
        ///} if
        ///
        ///% [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PdfxDefinition {
            get {
                return ResourceManager.GetString("PdfxDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die %!PS
        ////stampstring ([STAMPSTRING]) def
        ////fontname /[FONTNAME] def
        ////fontsize [FONTSIZE] def
        ////fontcolor {[FONTCOLOR]} def
        ////ISOLatin1Encoding [
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /space/exclam/quotedbl/numbersign/dollar/percent/ampersand/quoteright
        ///    /parenle [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PostScriptStamp {
            get {
                return ResourceManager.GetString("PostScriptStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] WebCoatedFOGRA28 {
            get {
                object obj = ResourceManager.GetObject("WebCoatedFOGRA28", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
